// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1SvZBVO8NpTekQPnSysH_HXHTBtOw4I',
    appId: '1:78743566270:web:1630f1f86ade2ff70debef',
    messagingSenderId: '78743566270',
    projectId: 'dalelak-b6812',
    authDomain: 'dalelak-b6812.firebaseapp.com',
    storageBucket: 'dalelak-b6812.firebasestorage.app',
    measurementId: 'G-BSX7VR9H9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvEWqjwNMUGTziQbDgyuevQq4DYpPGQ_g',
    appId: '1:78743566270:android:178c26981dc7f34e0debef',
    messagingSenderId: '78743566270',
    projectId: 'dalelak-b6812',
    storageBucket: 'dalelak-b6812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaq2PeBN5QrP2EwUTMFqce2dE3yNew1sU',
    appId: '1:78743566270:ios:90ce6a7c1637111b0debef',
    messagingSenderId: '78743566270',
    projectId: 'dalelak-b6812',
    storageBucket: 'dalelak-b6812.firebasestorage.app',
    iosClientId: '78743566270-vvtg7mr1f4rucaao96h6vd54liq9ib2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaq2PeBN5QrP2EwUTMFqce2dE3yNew1sU',
    appId: '1:78743566270:ios:90ce6a7c1637111b0debef',
    messagingSenderId: '78743566270',
    projectId: 'dalelak-b6812',
    storageBucket: 'dalelak-b6812.firebasestorage.app',
    iosClientId: '78743566270-vvtg7mr1f4rucaao96h6vd54liq9ib2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1SvZBVO8NpTekQPnSysH_HXHTBtOw4I',
    appId: '1:78743566270:web:0ee93f027d725e3e0debef',
    messagingSenderId: '78743566270',
    projectId: 'dalelak-b6812',
    authDomain: 'dalelak-b6812.firebaseapp.com',
    storageBucket: 'dalelak-b6812.firebasestorage.app',
    measurementId: 'G-1HLC6C8L3V',
  );
}
